/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.bean.Multa;
import model.dao.MultaDAO;


public class TelaPopupMulta extends javax.swing.JFrame {

    int flag =0;
    String cod_multa;
    Multa mul = new Multa();
    MultaDAO multadao = new MultaDAO();
    
    public TelaPopupMulta(String codigo) throws SQLException {
        initComponents();
        
        cod_multa = codigo;
        int cod = Integer.parseInt(cod_multa.trim());
        mul = multadao.buscaCadastroPorCodigo(cod);
        
        jTextFieldNumero.setText(Long.toString(mul.getNumMul()));
        jTextFieldNumero.setEditable(false);
        jTextFieldLocal.setText(mul.getLocMul());
        jTextFieldLocal.setEditable(false);
        jTextFieldcidade.setText(mul.getCidMul());
        jTextFieldcidade.setEditable(false);
        jTextFieldestado.setText(mul.getEstMul());
        jTextFieldestado.setEditable(false);
        jTextFielddescricao.setText(mul.getDescMult());
        jTextFielddescricao.setEditable(false);
        jTextFieldorgao.setText(mul.getOrgMul());
        jTextFieldorgao.setEditable(false);
        jTextFieldidmulta.setText(Integer.toString(mul.getIdMul()));
        jTextFieldidmulta.setEditable(false);
    }

    private TelaPopupMulta() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lnumero = new javax.swing.JLabel();
        lorgao = new javax.swing.JLabel();
        ldata = new javax.swing.JLabel();
        lcidade = new javax.swing.JLabel();
        lestado = new javax.swing.JLabel();
        llocal = new javax.swing.JLabel();
        ldescricao = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldorgao = new javax.swing.JTextField();
        jTextFielddata = new javax.swing.JTextField();
        jTextFieldcidade = new javax.swing.JTextField();
        jTextFieldestado = new javax.swing.JTextField();
        jTextFieldLocal = new javax.swing.JTextField();
        jTextFielddescricao = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        jTextFieldidmulta = new javax.swing.JFormattedTextField();
        lidmulta = new javax.swing.JLabel();
        javax.swing.JLabel jLabelFundoLogin = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        lnumero.setText("Número:");
        getContentPane().add(lnumero);
        lnumero.setBounds(10, 60, 210, 20);

        lorgao.setText("Órgão autuador:");
        getContentPane().add(lorgao);
        lorgao.setBounds(230, 60, 180, 20);

        ldata.setText("Data:");
        getContentPane().add(ldata);
        ldata.setBounds(10, 120, 140, 20);

        lcidade.setText("Cidade:");
        getContentPane().add(lcidade);
        lcidade.setBounds(10, 180, 170, 20);

        lestado.setText("Estado:");
        getContentPane().add(lestado);
        lestado.setBounds(250, 180, 130, 20);

        llocal.setText("Local da infração:");
        getContentPane().add(llocal);
        llocal.setBounds(190, 120, 250, 20);

        ldescricao.setText("Descrição:");
        getContentPane().add(ldescricao);
        ldescricao.setBounds(10, 240, 260, 20);

        jTextFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNumero);
        jTextFieldNumero.setBounds(10, 80, 210, 30);
        getContentPane().add(jTextFieldorgao);
        jTextFieldorgao.setBounds(230, 80, 210, 30);
        getContentPane().add(jTextFielddata);
        jTextFielddata.setBounds(10, 140, 150, 30);

        jTextFieldcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldcidade);
        jTextFieldcidade.setBounds(10, 200, 220, 30);

        jTextFieldestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldestadoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldestado);
        jTextFieldestado.setBounds(250, 200, 190, 30);
        getContentPane().add(jTextFieldLocal);
        jTextFieldLocal.setBounds(190, 140, 250, 30);

        jTextFielddescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddescricaoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFielddescricao);
        jTextFielddescricao.setBounds(10, 260, 430, 30);

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Sair");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(330, 300, 110, 40);

        jTextFieldidmulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidmultaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldidmulta);
        jTextFieldidmulta.setBounds(10, 20, 150, 30);

        lidmulta.setText("ID:");
        getContentPane().add(lidmulta);
        lidmulta.setBounds(10, 0, 150, 20);

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo800500.png"))); // NOI18N
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(0, 0, 450, 350);

        setSize(new java.awt.Dimension(462, 386));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
         
    private void jTextFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jTextFielddescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddescricaoActionPerformed

    private void jTextFieldcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcidadeActionPerformed

    private void jTextFieldestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldestadoActionPerformed

    private void jTextFieldidmultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidmultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldidmultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPopupMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPopupMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPopupMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPopupMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPopupMulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField jTextFieldLocal;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldcidade;
    private javax.swing.JTextField jTextFielddata;
    private javax.swing.JTextField jTextFielddescricao;
    private javax.swing.JTextField jTextFieldestado;
    private javax.swing.JFormattedTextField jTextFieldidmulta;
    private javax.swing.JTextField jTextFieldorgao;
    private javax.swing.JLabel lcidade;
    private javax.swing.JLabel ldata;
    private javax.swing.JLabel ldescricao;
    private javax.swing.JLabel lestado;
    private javax.swing.JLabel lidmulta;
    private javax.swing.JLabel llocal;
    private javax.swing.JLabel lnumero;
    private javax.swing.JLabel lorgao;
    // End of variables declaration//GEN-END:variables


    

}
