/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Veiculo;
import model.dao.VeiculoDAO;

/**
 *
 * @author konno
 */
public class TelaVeiculosInserir extends javax.swing.JFrame {

    public TelaVeiculosInserir() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lPlaca = new javax.swing.JLabel();
        lrenavan = new javax.swing.JLabel();
        lchassi = new javax.swing.JLabel();
        lano = new javax.swing.JLabel();
        lmarca = new javax.swing.JLabel();
        lmodelo = new javax.swing.JLabel();
        lcategoria = new javax.swing.JLabel();
        lcambio = new javax.swing.JLabel();
        AltCidadeCliente = new javax.swing.JLabel();
        lmotor = new javax.swing.JLabel();
        lar = new javax.swing.JLabel();
        AltNumpreco = new javax.swing.JLabel();
        AltValCliente = new javax.swing.JLabel();
        jTextFieldPlaca = new javax.swing.JTextField();
        jTextFieldrenavan = new javax.swing.JTextField();
        jTextFieldchassi = new javax.swing.JTextField();
        jTextFieldano = new javax.swing.JTextField();
        jTextFieldmarca = new javax.swing.JTextField();
        jTextFieldmodelo = new javax.swing.JTextField();
        jTextFieldcategoria = new javax.swing.JTextField();
        jTextFieldcambio = new javax.swing.JTextField();
        jTextFieldqtd = new javax.swing.JTextField();
        jTextFieldmotor = new javax.swing.JTextField();
        jTextFieldar = new javax.swing.JTextField();
        jTextFieldpreco = new javax.swing.JTextField();
        jTextFieldstatus = new javax.swing.JFormattedTextField();
        btnInserir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldcor = new javax.swing.JTextField();
        lcor = new javax.swing.JLabel();
        javax.swing.JLabel jLabelFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lPlaca.setText("Placa:");
        getContentPane().add(lPlaca);
        lPlaca.setBounds(40, 130, 40, 20);

        lrenavan.setText("RENAVAN:");
        getContentPane().add(lrenavan);
        lrenavan.setBounds(360, 130, 70, 20);

        lchassi.setText("CHASSI:");
        getContentPane().add(lchassi);
        lchassi.setBounds(570, 130, 50, 20);

        lano.setText("Ano:");
        getContentPane().add(lano);
        lano.setBounds(40, 200, 100, 20);

        lmarca.setText("Marca:");
        getContentPane().add(lmarca);
        lmarca.setBounds(260, 200, 80, 20);

        lmodelo.setText("Modelo:");
        getContentPane().add(lmodelo);
        lmodelo.setBounds(460, 200, 40, 20);

        lcategoria.setText("Categoria:");
        getContentPane().add(lcategoria);
        lcategoria.setBounds(40, 270, 70, 20);

        lcambio.setText("Cambio:");
        getContentPane().add(lcambio);
        lcambio.setBounds(320, 270, 50, 20);

        AltCidadeCliente.setText("Qtd. passageiros:");
        getContentPane().add(AltCidadeCliente);
        AltCidadeCliente.setBounds(500, 270, 90, 20);

        lmotor.setText("Motor:");
        getContentPane().add(lmotor);
        lmotor.setBounds(680, 200, 50, 20);

        lar.setText("Ar-condicionado:");
        getContentPane().add(lar);
        lar.setBounds(630, 270, 100, 20);

        AltNumpreco.setText("Preço/diária:");
        getContentPane().add(AltNumpreco);
        AltNumpreco.setBounds(160, 340, 70, 20);

        AltValCliente.setText("Status:");
        getContentPane().add(AltValCliente);
        AltValCliente.setBounds(340, 340, 35, 20);

        jTextFieldPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPlaca);
        jTextFieldPlaca.setBounds(40, 150, 300, 30);
        getContentPane().add(jTextFieldrenavan);
        jTextFieldrenavan.setBounds(360, 150, 180, 30);
        getContentPane().add(jTextFieldchassi);
        jTextFieldchassi.setBounds(570, 150, 190, 30);

        jTextFieldano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldanoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldano);
        jTextFieldano.setBounds(40, 220, 190, 30);
        getContentPane().add(jTextFieldmarca);
        jTextFieldmarca.setBounds(260, 220, 170, 30);
        getContentPane().add(jTextFieldmodelo);
        jTextFieldmodelo.setBounds(460, 220, 190, 30);

        jTextFieldcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldcategoria);
        jTextFieldcategoria.setBounds(40, 290, 250, 30);

        jTextFieldcambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcambioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldcambio);
        jTextFieldcambio.setBounds(320, 290, 150, 30);
        getContentPane().add(jTextFieldqtd);
        jTextFieldqtd.setBounds(500, 290, 110, 30);
        getContentPane().add(jTextFieldmotor);
        jTextFieldmotor.setBounds(680, 220, 80, 30);
        getContentPane().add(jTextFieldar);
        jTextFieldar.setBounds(630, 290, 130, 30);

        jTextFieldpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldprecoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldpreco);
        jTextFieldpreco.setBounds(160, 360, 160, 30);

        jTextFieldstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldstatusActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldstatus);
        jTextFieldstatus.setBounds(340, 360, 150, 30);

        btnInserir.setBackground(new java.awt.Color(255, 0, 0));
        btnInserir.setForeground(new java.awt.Color(255, 255, 255));
        btnInserir.setText("Adicionar");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btnInserir);
        btnInserir.setBounds(660, 440, 110, 40);

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(530, 440, 110, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem-Título-2.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(310, 40, 150, 50);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem-Título-3.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(320, 440, 140, 60);

        jTextFieldcor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldcor);
        jTextFieldcor.setBounds(40, 360, 100, 30);

        lcor.setText("Cor:");
        getContentPane().add(lcor);
        lcor.setBounds(40, 340, 70, 20);

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo800500.png"))); // NOI18N
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void  salvar() throws ParseException, ParseException, SQLException{
        try{
            Veiculo vei = new Veiculo();
            vei.setPlaVei(jTextFieldPlaca.getText());
            vei.setRenVei(Long.parseLong(jTextFieldrenavan.getText()));
            vei.setAnoVei(Integer.parseInt(jTextFieldano.getText()));
            vei.setChaVei(jTextFieldchassi.getText());
            vei.setMarVei(jTextFieldmarca.getText());
            vei.setModVei(jTextFieldmodelo.getText());
            vei.setMotVei(jTextFieldmotor.getText());
            vei.setCorVei(jTextFieldcor.getText());
            vei.setCatVei(jTextFieldcategoria.getText());
            vei.setCamVei(jTextFieldcambio.getText());
            vei.setPasVei(Integer.parseInt(jTextFieldqtd.getText()));
            vei.setArVei(jTextFieldar.getText());
            vei.setDiaVei(Float.parseFloat(jTextFieldpreco.getText()));
            vei.setStaVei(jTextFieldstatus.getText());

            VeiculoDAO dao = new VeiculoDAO();
            dao.novo(vei);
            JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!\n\n");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Erro ao salvar dados\n\n" + e);
        }
    }
     boolean verificavazio(){
         return (!jTextFieldPlaca.getText().equals("") || !jTextFieldrenavan.getText().equals("")
                || !jTextFieldchassi.getText().equals("") || !jTextFieldmarca.getText().equals("")
                || !jTextFieldmodelo.getText().equals("") || !jTextFieldano.getText().equals("")
                || !jTextFieldcategoria.getText().equals("") || !jTextFieldcambio.getText().equals("")
                || !jTextFieldqtd.getText().equals("") || !jTextFieldmotor.getText().equals("")
                || !jTextFieldar.getText().equals("") || !jTextFieldpreco.getText().equals("")
                || !jTextFieldstatus.getText().equals(""));
     }       
             
         
 
    private void jTextFieldPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlacaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        try {
            TelaVeiculos tela = new TelaVeiculos();
            tela.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TelaGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jTextFieldstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldstatusActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        if(!verificavazio()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos. ");
        }else{
               
                try {
                    salvar();
                    TelaVeiculos tela = new TelaVeiculos();
                    tela.setVisible(true);
                    dispose();
                    
                   
                   
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao salvar dados\n\n" + ex);
                } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null, "Erro ao salvar dados\n\n" + ex);
                }
            }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void jTextFieldprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldprecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldprecoActionPerformed

    private void jTextFieldcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcategoriaActionPerformed

    private void jTextFieldcambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcambioActionPerformed

    private void jTextFieldanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldanoActionPerformed

    private void jTextFieldcorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculosInserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculosInserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculosInserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculosInserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVeiculosInserir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AltCidadeCliente;
    private javax.swing.JLabel AltNumpreco;
    private javax.swing.JLabel AltValCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jTextFieldano;
    private javax.swing.JTextField jTextFieldar;
    private javax.swing.JTextField jTextFieldcambio;
    private javax.swing.JTextField jTextFieldcategoria;
    private javax.swing.JTextField jTextFieldchassi;
    private javax.swing.JTextField jTextFieldcor;
    private javax.swing.JTextField jTextFieldmarca;
    private javax.swing.JTextField jTextFieldmodelo;
    private javax.swing.JTextField jTextFieldmotor;
    private javax.swing.JTextField jTextFieldpreco;
    private javax.swing.JTextField jTextFieldqtd;
    private javax.swing.JTextField jTextFieldrenavan;
    private javax.swing.JFormattedTextField jTextFieldstatus;
    private javax.swing.JLabel lPlaca;
    private javax.swing.JLabel lano;
    private javax.swing.JLabel lar;
    private javax.swing.JLabel lcambio;
    private javax.swing.JLabel lcategoria;
    private javax.swing.JLabel lchassi;
    private javax.swing.JLabel lcor;
    private javax.swing.JLabel lmarca;
    private javax.swing.JLabel lmodelo;
    private javax.swing.JLabel lmotor;
    private javax.swing.JLabel lrenavan;
    // End of variables declaration//GEN-END:variables


    

}
