/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.awt.Desktop;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Locacao;
import model.dao.LocacaoDAO;





public class TelaRelatorio extends javax.swing.JFrame {

     String cod_loc;
    
   
    public TelaRelatorio() throws SQLException {
        initComponents();
        setLocationRelativeTo(this);
        
        
        DefaultTableModel modelo = (DefaultTableModel)tabelaLoc.getModel();
        tabelaLoc.setRowSorter(new TableRowSorter(modelo));

        exibirDados();
    }

    
      public void exibirDados() throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaLoc.getModel();
        modelo.setNumRows(0);
        LocacaoDAO locacao = new LocacaoDAO();

        for (Locacao loc : locacao.listar()) {

            modelo.addRow(new Object[]{
                loc.getIdLoc(),
                loc.getQtdDias_locacao(),
                loc.getValorTotal_locacao()
            });

        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnImprimir = new javax.swing.JButton();
        BtnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLoc = new javax.swing.JTable();
        BtnVoltar = new javax.swing.JButton();
        pesquisarLocacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        BtnImprimir.setBackground(new java.awt.Color(255, 0, 0));
        BtnImprimir.setForeground(new java.awt.Color(255, 255, 255));
        BtnImprimir.setText("Imprimir");
        BtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnImprimir);
        BtnImprimir.setBounds(710, 410, 170, 40);

        BtnPesquisar.setBackground(new java.awt.Color(255, 0, 0));
        BtnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        BtnPesquisar.setText("Pesquisar");
        BtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnPesquisar);
        BtnPesquisar.setBounds(290, 50, 90, 30);

        tabelaLoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID locação", "Qtd. de Dias", "Valor total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaLoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaLocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaLoc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 90, 910, 300);

        BtnVoltar.setBackground(new java.awt.Color(255, 0, 0));
        BtnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnVoltar);
        BtnVoltar.setBounds(510, 410, 170, 40);

        pesquisarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarLocacaoActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisarLocacao);
        pesquisarLocacao.setBounds(50, 50, 230, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem-Título-3.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 460, 170, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem-Título-2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 10, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo1000500.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 500);

        setSize(new java.awt.Dimension(1016, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimirActionPerformed
        

    }//GEN-LAST:event_BtnImprimirActionPerformed
public void pesquisarLoc(int chave) throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaLoc.getModel();
        modelo.setNumRows(0);
        LocacaoDAO locacao = new LocacaoDAO();

        for (Locacao loc : locacao.pesquisar(chave)) {

            modelo.addRow(new Object[]{
                loc.getIdLoc(),
                loc.getQtdDias_locacao(),
                loc.getValorTotal_locacao()
            });
        }
    }
    private void BtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarActionPerformed
         try {
             pesquisarLoc(Integer.parseInt(pesquisarLocacao.getText()));
         } catch (SQLException ex) {
             Logger.getLogger(TelaRelatorio.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_BtnPesquisarActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
       TelaGerente tela = new TelaGerente();
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void pesquisarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarLocacaoActionPerformed

    private void tabelaLocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaLocMouseClicked
        
         cod_loc = " "+ tabelaLoc.getValueAt(tabelaLoc.getSelectedRow(),0);  
    }//GEN-LAST:event_tabelaLocMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
         
            public void run() {
                try {
                    new TelaRelatorio().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaRelatorio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnImprimir;
    private javax.swing.JButton BtnPesquisar;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pesquisarLocacao;
    private javax.swing.JTable tabelaLoc;
    // End of variables declaration//GEN-END:variables
}
