/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author konno
 */
public class TelaAtendente extends javax.swing.JFrame {

    /**
     * Creates new form TelaAtendente
     */
    public TelaAtendente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonLocacao = new javax.swing.JButton();
        jButtonsimulacao = new javax.swing.JButton();
        jButtonDevolucao = new javax.swing.JButton();
        jButtonMultas = new javax.swing.JButton();
        jButtonClientes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/biell.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 360, 230, 80);

        jButtonLocacao.setBackground(new java.awt.Color(255, 0, 0));
        jButtonLocacao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLocacao.setText("Locação");
        getContentPane().add(jButtonLocacao);
        jButtonLocacao.setBounds(360, 150, 150, 40);

        jButtonsimulacao.setBackground(new java.awt.Color(255, 0, 0));
        jButtonsimulacao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonsimulacao.setText("Simulação");
        getContentPane().add(jButtonsimulacao);
        jButtonsimulacao.setBounds(140, 150, 150, 40);

        jButtonDevolucao.setBackground(new java.awt.Color(255, 0, 0));
        jButtonDevolucao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDevolucao.setText("Devolução");
        getContentPane().add(jButtonDevolucao);
        jButtonDevolucao.setBounds(140, 230, 150, 40);

        jButtonMultas.setBackground(new java.awt.Color(255, 0, 0));
        jButtonMultas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMultas.setText("Multas");
        jButtonMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMultas);
        jButtonMultas.setBounds(360, 230, 150, 40);

        jButtonClientes.setBackground(new java.awt.Color(255, 0, 0));
        jButtonClientes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClientes.setText("Clientes");
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClientes);
        jButtonClientes.setBounds(250, 300, 150, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alocar.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 30, 242, 90);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 657, 439);

        setSize(new java.awt.Dimension(673, 478));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        try {
            TelaCliente tela = new TelaCliente();
            tela.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TelaAtendente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultasActionPerformed
        try {
            TelaMultas tela = new TelaMultas();
            tela.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TelaAtendente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonMultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonDevolucao;
    private javax.swing.JButton jButtonLocacao;
    private javax.swing.JButton jButtonMultas;
    private javax.swing.JButton jButtonsimulacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFundo;
    // End of variables declaration//GEN-END:variables
}
