/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Checklist;
import model.bean.Cliente;
import model.dao.ChecklistDAO;
import model.dao.ClienteDAO;

/**
 *
 * @author konno
 */
public class TelaCheckList extends javax.swing.JFrame {

    /**
     * Creates new form TelaCheckList
     */
    public TelaCheckList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        buttonGroup20 = new javax.swing.ButtonGroup();
        buttonGroup21 = new javax.swing.ButtonGroup();
        buttonGroup22 = new javax.swing.ButtonGroup();
        buttonGroup23 = new javax.swing.ButtonGroup();
        buttonGroup24 = new javax.swing.ButtonGroup();
        buttonGroup25 = new javax.swing.ButtonGroup();
        buttonGroup26 = new javax.swing.ButtonGroup();
        buttonGroup27 = new javax.swing.ButtonGroup();
        buttonGroup28 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        DefRetrovisor = new javax.swing.JRadioButton();
        OkRetrovisor = new javax.swing.JRadioButton();
        OkBuzina = new javax.swing.JRadioButton();
        Defbuzina = new javax.swing.JRadioButton();
        OkAcendedor = new javax.swing.JRadioButton();
        DefAcendedor = new javax.swing.JRadioButton();
        DefSens = new javax.swing.JRadioButton();
        OkSens = new javax.swing.JRadioButton();
        DefRadio = new javax.swing.JRadioButton();
        OkRadio = new javax.swing.JRadioButton();
        DefVidro = new javax.swing.JRadioButton();
        OkVidro = new javax.swing.JRadioButton();
        DefPisca = new javax.swing.JRadioButton();
        OkPisca = new javax.swing.JRadioButton();
        DefBateria = new javax.swing.JRadioButton();
        OkBateria = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        DefFarol = new javax.swing.JRadioButton();
        OkFarol = new javax.swing.JRadioButton();
        OkLuz1 = new javax.swing.JRadioButton();
        DefLuz1 = new javax.swing.JRadioButton();
        OkLanterna = new javax.swing.JRadioButton();
        DefLanterna = new javax.swing.JRadioButton();
        OkLuz2 = new javax.swing.JRadioButton();
        DefLuz2 = new javax.swing.JRadioButton();
        OkSetas = new javax.swing.JRadioButton();
        DefSetas = new javax.swing.JRadioButton();
        OkLuzTeto = new javax.swing.JRadioButton();
        DefLuzTeto = new javax.swing.JRadioButton();
        OkAr = new javax.swing.JRadioButton();
        DefAr = new javax.swing.JRadioButton();
        OkPart = new javax.swing.JRadioButton();
        DefPart = new javax.swing.JRadioButton();
        Okteto = new javax.swing.JRadioButton();
        DefTeto = new javax.swing.JRadioButton();
        OkLimpador = new javax.swing.JRadioButton();
        DefLimpador = new javax.swing.JRadioButton();
        OkRelogio = new javax.swing.JRadioButton();
        DefRelogio = new javax.swing.JRadioButton();
        OkAlarme = new javax.swing.JRadioButton();
        DefAlarme = new javax.swing.JRadioButton();
        OkTravas = new javax.swing.JRadioButton();
        DefTravas = new javax.swing.JRadioButton();
        OkTampa = new javax.swing.JRadioButton();
        DefTampa = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton104 = new javax.swing.JRadioButton();
        jRadioButton105 = new javax.swing.JRadioButton();
        jRadioButton106 = new javax.swing.JRadioButton();
        jRadioButton107 = new javax.swing.JRadioButton();
        jRadioButton108 = new javax.swing.JRadioButton();
        jRadioButton109 = new javax.swing.JRadioButton();
        jRadioButton110 = new javax.swing.JRadioButton();
        jRadioButton111 = new javax.swing.JRadioButton();
        jRadioButton112 = new javax.swing.JRadioButton();
        jRadioButton113 = new javax.swing.JRadioButton();
        jRadioButton114 = new javax.swing.JRadioButton();
        jRadioButton115 = new javax.swing.JRadioButton();
        jRadioButton116 = new javax.swing.JRadioButton();
        jRadioButton117 = new javax.swing.JRadioButton();
        jRadioButton118 = new javax.swing.JRadioButton();
        jRadioButton119 = new javax.swing.JRadioButton();
        jRadioButton120 = new javax.swing.JRadioButton();
        jRadioButton121 = new javax.swing.JRadioButton();
        jRadioButton122 = new javax.swing.JRadioButton();
        jRadioButton123 = new javax.swing.JRadioButton();
        jRadioButton124 = new javax.swing.JRadioButton();
        jRadioButton125 = new javax.swing.JRadioButton();
        jRadioButton126 = new javax.swing.JRadioButton();
        jRadioButton127 = new javax.swing.JRadioButton();
        jRadioButton128 = new javax.swing.JRadioButton();
        jRadioButton129 = new javax.swing.JRadioButton();
        jRadioButton130 = new javax.swing.JRadioButton();
        jRadioButton131 = new javax.swing.JRadioButton();
        jRadioButton132 = new javax.swing.JRadioButton();
        jRadioButton133 = new javax.swing.JRadioButton();
        jRadioButton134 = new javax.swing.JRadioButton();
        jRadioButton135 = new javax.swing.JRadioButton();
        jRadioButton136 = new javax.swing.JRadioButton();
        jRadioButton137 = new javax.swing.JRadioButton();
        jRadioButton138 = new javax.swing.JRadioButton();
        jRadioButton139 = new javax.swing.JRadioButton();
        jRadioButton140 = new javax.swing.JRadioButton();
        jRadioButton141 = new javax.swing.JRadioButton();
        jRadioButton142 = new javax.swing.JRadioButton();
        jRadioButton143 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        OkAssento = new javax.swing.JRadioButton();
        DefAssento = new javax.swing.JRadioButton();
        jRadioButton144 = new javax.swing.JRadioButton();
        jRadioButton145 = new javax.swing.JRadioButton();
        OkCadeirinha = new javax.swing.JRadioButton();
        DefCadeirinha = new javax.swing.JRadioButton();
        jRadioButton146 = new javax.swing.JRadioButton();
        jRadioButton147 = new javax.swing.JRadioButton();
        OkBebe = new javax.swing.JRadioButton();
        DefBebe = new javax.swing.JRadioButton();
        jRadioButton148 = new javax.swing.JRadioButton();
        jRadioButton149 = new javax.swing.JRadioButton();
        OkGPS = new javax.swing.JRadioButton();
        DefGPS = new javax.swing.JRadioButton();
        jRadioButton150 = new javax.swing.JRadioButton();
        jRadioButton151 = new javax.swing.JRadioButton();
        OkWifi = new javax.swing.JRadioButton();
        DefWifi = new javax.swing.JRadioButton();
        jRadioButton152 = new javax.swing.JRadioButton();
        jRadioButton153 = new javax.swing.JRadioButton();
        OkKit = new javax.swing.JRadioButton();
        DefKit = new javax.swing.JRadioButton();
        jRadioButton154 = new javax.swing.JRadioButton();
        jRadioButton155 = new javax.swing.JRadioButton();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Retrovisor Manual/ Elétrico");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 190, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("luz de re");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 180, 190, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Farol baixo/alto /lampejo ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 120, 190, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Lanternas/ luz placa");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 140, 190, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("luz de freio/ break light");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 160, 190, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Setas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 200, 190, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("luz do teto/ leitura");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 220, 190, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Ar Condicionado");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 240, 190, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Partida e Func. Motor");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 260, 190, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Teto/ Painel / Quebra Sol");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 280, 190, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Limpadores");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 300, 190, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Relogio/ Comp. de Bordo");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 320, 190, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Alarme Original/ Outros");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 340, 190, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Travas Elétricas");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(20, 360, 190, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Tampa do Porta luvas");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 380, 190, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Pisca Alerta");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 400, 190, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Acendedor de Cigarro ");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(20, 420, 190, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Sensor/ Camera de ré");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(380, 70, 150, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Radio/ DVD/ CD/ MP3");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(380, 90, 138, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Vidros Elétricos");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(380, 110, 150, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Bateria");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(380, 130, 150, 20);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Buzina");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(380, 150, 150, 20);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/div.png"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(360, 70, 10, 370);

        buttonGroup1.add(DefRetrovisor);
        DefRetrovisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefRetrovisorActionPerformed(evt);
            }
        });
        getContentPane().add(DefRetrovisor);
        DefRetrovisor.setBounds(240, 100, 30, 21);

        buttonGroup1.add(OkRetrovisor);
        OkRetrovisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkRetrovisorActionPerformed(evt);
            }
        });
        getContentPane().add(OkRetrovisor);
        OkRetrovisor.setBounds(210, 100, 30, 21);

        buttonGroup22.add(OkBuzina);
        OkBuzina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkBuzinaActionPerformed(evt);
            }
        });
        getContentPane().add(OkBuzina);
        OkBuzina.setBounds(530, 150, 30, 21);

        buttonGroup22.add(Defbuzina);
        Defbuzina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefbuzinaActionPerformed(evt);
            }
        });
        getContentPane().add(Defbuzina);
        Defbuzina.setBounds(560, 150, 30, 21);

        buttonGroup17.add(OkAcendedor);
        OkAcendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkAcendedorActionPerformed(evt);
            }
        });
        getContentPane().add(OkAcendedor);
        OkAcendedor.setBounds(210, 420, 30, 21);

        buttonGroup17.add(DefAcendedor);
        DefAcendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefAcendedorActionPerformed(evt);
            }
        });
        getContentPane().add(DefAcendedor);
        DefAcendedor.setBounds(240, 420, 30, 21);

        buttonGroup18.add(DefSens);
        DefSens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefSensActionPerformed(evt);
            }
        });
        getContentPane().add(DefSens);
        DefSens.setBounds(560, 70, 30, 21);

        buttonGroup18.add(OkSens);
        OkSens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkSensActionPerformed(evt);
            }
        });
        getContentPane().add(OkSens);
        OkSens.setBounds(530, 70, 30, 21);

        buttonGroup19.add(DefRadio);
        DefRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefRadioActionPerformed(evt);
            }
        });
        getContentPane().add(DefRadio);
        DefRadio.setBounds(560, 90, 30, 21);

        buttonGroup19.add(OkRadio);
        OkRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkRadioActionPerformed(evt);
            }
        });
        getContentPane().add(OkRadio);
        OkRadio.setBounds(530, 90, 30, 21);

        buttonGroup20.add(DefVidro);
        DefVidro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefVidroActionPerformed(evt);
            }
        });
        getContentPane().add(DefVidro);
        DefVidro.setBounds(560, 110, 30, 21);

        buttonGroup20.add(OkVidro);
        OkVidro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkVidroActionPerformed(evt);
            }
        });
        getContentPane().add(OkVidro);
        OkVidro.setBounds(530, 110, 30, 21);

        buttonGroup16.add(DefPisca);
        DefPisca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefPiscaActionPerformed(evt);
            }
        });
        getContentPane().add(DefPisca);
        DefPisca.setBounds(240, 400, 30, 21);

        buttonGroup16.add(OkPisca);
        OkPisca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkPiscaActionPerformed(evt);
            }
        });
        getContentPane().add(OkPisca);
        OkPisca.setBounds(210, 400, 30, 21);

        buttonGroup21.add(DefBateria);
        DefBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefBateriaActionPerformed(evt);
            }
        });
        getContentPane().add(DefBateria);
        DefBateria.setBounds(560, 130, 30, 21);

        buttonGroup21.add(OkBateria);
        OkBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkBateriaActionPerformed(evt);
            }
        });
        getContentPane().add(OkBateria);
        OkBateria.setBounds(530, 130, 30, 21);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("OK");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(530, 50, 20, 14);

        jLabel26.setText("DEF");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(560, 50, 30, 14);

        jLabel27.setText("DEF");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(320, 80, 30, 14);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("OK");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(290, 80, 20, 14);

        jLabel29.setFont(new java.awt.Font("Castellar", 1, 20)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("ADICIONAIS");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(370, 180, 450, 30);

        jLabel30.setText("Cadeirinha Para criança ");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(460, 280, 140, 14);

        jLabel31.setText("Assento de elevação para crianças");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(460, 240, 170, 14);

        jLabel32.setText("Bebê conforto");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(460, 320, 180, 20);

        jLabel33.setText("GPS");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(460, 360, 180, 20);

        jLabel34.setText("WI-FI");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(460, 390, 170, 30);

        jLabel35.setText("Kit Connect");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(460, 430, 170, 20);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/elevação2.png"))); // NOI18N
        getContentPane().add(jLabel36);
        jLabel36.setBounds(390, 220, 40, 40);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gps2.png"))); // NOI18N
        getContentPane().add(jLabel39);
        jLabel39.setBounds(400, 350, 40, 30);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/wifi2.png"))); // NOI18N
        getContentPane().add(jLabel40);
        jLabel40.setBounds(400, 390, 50, 30);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadeirinha2.png"))); // NOI18N
        getContentPane().add(jLabel41);
        jLabel41.setBounds(390, 260, 50, 40);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bebeconf.png"))); // NOI18N
        jLabel42.setToolTipText("");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(400, 300, 40, 40);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/kitconnec.png"))); // NOI18N
        getContentPane().add(jLabel43);
        jLabel43.setBounds(390, 430, 52, 30);

        jLabel37.setText("DEF");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(240, 80, 30, 14);

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("OK");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(210, 80, 20, 14);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem-Título-2.png"))); // NOI18N
        getContentPane().add(jLabel44);
        jLabel44.setBounds(310, 0, 170, 42);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem-Título-3.png"))); // NOI18N
        getContentPane().add(jLabel45);
        jLabel45.setBounds(290, 450, 140, 50);

        buttonGroup2.add(DefFarol);
        DefFarol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefFarolActionPerformed(evt);
            }
        });
        getContentPane().add(DefFarol);
        DefFarol.setBounds(240, 120, 30, 21);

        buttonGroup2.add(OkFarol);
        OkFarol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkFarolActionPerformed(evt);
            }
        });
        getContentPane().add(OkFarol);
        OkFarol.setBounds(210, 120, 30, 21);

        buttonGroup3.add(OkLuz1);
        OkLuz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkLuz1ActionPerformed(evt);
            }
        });
        getContentPane().add(OkLuz1);
        OkLuz1.setBounds(210, 160, 30, 21);

        buttonGroup3.add(DefLuz1);
        DefLuz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefLuz1ActionPerformed(evt);
            }
        });
        getContentPane().add(DefLuz1);
        DefLuz1.setBounds(240, 160, 30, 21);

        buttonGroup4.add(OkLanterna);
        OkLanterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkLanternaActionPerformed(evt);
            }
        });
        getContentPane().add(OkLanterna);
        OkLanterna.setBounds(210, 140, 30, 21);

        buttonGroup4.add(DefLanterna);
        DefLanterna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefLanternaActionPerformed(evt);
            }
        });
        getContentPane().add(DefLanterna);
        DefLanterna.setBounds(240, 140, 30, 21);

        buttonGroup5.add(OkLuz2);
        OkLuz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkLuz2ActionPerformed(evt);
            }
        });
        getContentPane().add(OkLuz2);
        OkLuz2.setBounds(210, 180, 30, 21);

        buttonGroup5.add(DefLuz2);
        DefLuz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefLuz2ActionPerformed(evt);
            }
        });
        getContentPane().add(DefLuz2);
        DefLuz2.setBounds(240, 180, 30, 21);

        buttonGroup6.add(OkSetas);
        OkSetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkSetasActionPerformed(evt);
            }
        });
        getContentPane().add(OkSetas);
        OkSetas.setBounds(210, 200, 30, 21);

        buttonGroup6.add(DefSetas);
        DefSetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefSetasActionPerformed(evt);
            }
        });
        getContentPane().add(DefSetas);
        DefSetas.setBounds(240, 200, 30, 21);

        buttonGroup7.add(OkLuzTeto);
        OkLuzTeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkLuzTetoActionPerformed(evt);
            }
        });
        getContentPane().add(OkLuzTeto);
        OkLuzTeto.setBounds(210, 220, 30, 21);

        buttonGroup7.add(DefLuzTeto);
        DefLuzTeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefLuzTetoActionPerformed(evt);
            }
        });
        getContentPane().add(DefLuzTeto);
        DefLuzTeto.setBounds(240, 220, 30, 21);

        buttonGroup8.add(OkAr);
        OkAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkArActionPerformed(evt);
            }
        });
        getContentPane().add(OkAr);
        OkAr.setBounds(210, 240, 30, 21);

        buttonGroup8.add(DefAr);
        DefAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefArActionPerformed(evt);
            }
        });
        getContentPane().add(DefAr);
        DefAr.setBounds(240, 240, 30, 21);

        buttonGroup9.add(OkPart);
        OkPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkPartActionPerformed(evt);
            }
        });
        getContentPane().add(OkPart);
        OkPart.setBounds(210, 260, 30, 21);

        buttonGroup9.add(DefPart);
        DefPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefPartActionPerformed(evt);
            }
        });
        getContentPane().add(DefPart);
        DefPart.setBounds(240, 260, 30, 21);

        buttonGroup10.add(Okteto);
        Okteto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OktetoActionPerformed(evt);
            }
        });
        getContentPane().add(Okteto);
        Okteto.setBounds(210, 280, 30, 21);

        buttonGroup10.add(DefTeto);
        DefTeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefTetoActionPerformed(evt);
            }
        });
        getContentPane().add(DefTeto);
        DefTeto.setBounds(240, 280, 30, 21);

        buttonGroup11.add(OkLimpador);
        OkLimpador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkLimpadorActionPerformed(evt);
            }
        });
        getContentPane().add(OkLimpador);
        OkLimpador.setBounds(210, 300, 30, 21);

        buttonGroup11.add(DefLimpador);
        DefLimpador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefLimpadorActionPerformed(evt);
            }
        });
        getContentPane().add(DefLimpador);
        DefLimpador.setBounds(240, 300, 30, 21);

        buttonGroup12.add(OkRelogio);
        OkRelogio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkRelogioActionPerformed(evt);
            }
        });
        getContentPane().add(OkRelogio);
        OkRelogio.setBounds(210, 320, 30, 21);

        buttonGroup12.add(DefRelogio);
        DefRelogio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefRelogioActionPerformed(evt);
            }
        });
        getContentPane().add(DefRelogio);
        DefRelogio.setBounds(240, 320, 30, 21);

        buttonGroup13.add(OkAlarme);
        OkAlarme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkAlarmeActionPerformed(evt);
            }
        });
        getContentPane().add(OkAlarme);
        OkAlarme.setBounds(210, 340, 30, 21);

        buttonGroup13.add(DefAlarme);
        DefAlarme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefAlarmeActionPerformed(evt);
            }
        });
        getContentPane().add(DefAlarme);
        DefAlarme.setBounds(240, 340, 30, 21);

        buttonGroup14.add(OkTravas);
        OkTravas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkTravasActionPerformed(evt);
            }
        });
        getContentPane().add(OkTravas);
        OkTravas.setBounds(210, 360, 30, 21);

        buttonGroup14.add(DefTravas);
        DefTravas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefTravasActionPerformed(evt);
            }
        });
        getContentPane().add(DefTravas);
        DefTravas.setBounds(240, 360, 30, 21);

        buttonGroup15.add(OkTampa);
        OkTampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkTampaActionPerformed(evt);
            }
        });
        getContentPane().add(OkTampa);
        OkTampa.setBounds(210, 380, 30, 21);

        buttonGroup15.add(DefTampa);
        DefTampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefTampaActionPerformed(evt);
            }
        });
        getContentPane().add(DefTampa);
        DefTampa.setBounds(240, 380, 30, 21);

        jRadioButton6.setEnabled(false);
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(290, 100, 30, 21);

        jRadioButton7.setEnabled(false);
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(320, 100, 30, 21);

        jRadioButton104.setEnabled(false);
        getContentPane().add(jRadioButton104);
        jRadioButton104.setBounds(320, 120, 30, 21);

        jRadioButton105.setEnabled(false);
        getContentPane().add(jRadioButton105);
        jRadioButton105.setBounds(290, 120, 30, 21);

        jRadioButton106.setEnabled(false);
        getContentPane().add(jRadioButton106);
        jRadioButton106.setBounds(290, 140, 30, 21);

        jRadioButton107.setEnabled(false);
        getContentPane().add(jRadioButton107);
        jRadioButton107.setBounds(320, 140, 30, 21);

        jRadioButton108.setEnabled(false);
        getContentPane().add(jRadioButton108);
        jRadioButton108.setBounds(320, 160, 30, 21);

        jRadioButton109.setEnabled(false);
        getContentPane().add(jRadioButton109);
        jRadioButton109.setBounds(290, 160, 30, 21);

        jRadioButton110.setEnabled(false);
        getContentPane().add(jRadioButton110);
        jRadioButton110.setBounds(290, 180, 30, 21);

        jRadioButton111.setEnabled(false);
        getContentPane().add(jRadioButton111);
        jRadioButton111.setBounds(320, 180, 30, 21);

        jRadioButton112.setEnabled(false);
        getContentPane().add(jRadioButton112);
        jRadioButton112.setBounds(320, 200, 30, 21);

        jRadioButton113.setEnabled(false);
        getContentPane().add(jRadioButton113);
        jRadioButton113.setBounds(290, 200, 30, 21);

        jRadioButton114.setEnabled(false);
        getContentPane().add(jRadioButton114);
        jRadioButton114.setBounds(290, 220, 30, 21);

        jRadioButton115.setEnabled(false);
        getContentPane().add(jRadioButton115);
        jRadioButton115.setBounds(320, 220, 30, 21);

        jRadioButton116.setEnabled(false);
        getContentPane().add(jRadioButton116);
        jRadioButton116.setBounds(320, 240, 30, 21);

        jRadioButton117.setEnabled(false);
        getContentPane().add(jRadioButton117);
        jRadioButton117.setBounds(290, 240, 30, 21);

        jRadioButton118.setEnabled(false);
        getContentPane().add(jRadioButton118);
        jRadioButton118.setBounds(290, 260, 30, 21);

        jRadioButton119.setEnabled(false);
        getContentPane().add(jRadioButton119);
        jRadioButton119.setBounds(320, 260, 30, 21);

        jRadioButton120.setEnabled(false);
        getContentPane().add(jRadioButton120);
        jRadioButton120.setBounds(320, 280, 30, 21);

        jRadioButton121.setEnabled(false);
        getContentPane().add(jRadioButton121);
        jRadioButton121.setBounds(290, 280, 30, 21);

        jRadioButton122.setEnabled(false);
        getContentPane().add(jRadioButton122);
        jRadioButton122.setBounds(290, 300, 30, 21);

        jRadioButton123.setEnabled(false);
        getContentPane().add(jRadioButton123);
        jRadioButton123.setBounds(320, 300, 30, 21);

        jRadioButton124.setEnabled(false);
        getContentPane().add(jRadioButton124);
        jRadioButton124.setBounds(320, 320, 30, 21);

        jRadioButton125.setEnabled(false);
        getContentPane().add(jRadioButton125);
        jRadioButton125.setBounds(290, 320, 30, 21);

        jRadioButton126.setEnabled(false);
        getContentPane().add(jRadioButton126);
        jRadioButton126.setBounds(290, 340, 30, 21);

        jRadioButton127.setEnabled(false);
        getContentPane().add(jRadioButton127);
        jRadioButton127.setBounds(320, 340, 30, 21);

        jRadioButton128.setEnabled(false);
        getContentPane().add(jRadioButton128);
        jRadioButton128.setBounds(320, 360, 30, 21);

        jRadioButton129.setEnabled(false);
        getContentPane().add(jRadioButton129);
        jRadioButton129.setBounds(290, 360, 30, 21);

        jRadioButton130.setEnabled(false);
        getContentPane().add(jRadioButton130);
        jRadioButton130.setBounds(290, 380, 30, 21);

        jRadioButton131.setEnabled(false);
        getContentPane().add(jRadioButton131);
        jRadioButton131.setBounds(320, 380, 30, 21);

        jRadioButton132.setEnabled(false);
        getContentPane().add(jRadioButton132);
        jRadioButton132.setBounds(320, 400, 30, 21);

        jRadioButton133.setEnabled(false);
        getContentPane().add(jRadioButton133);
        jRadioButton133.setBounds(290, 400, 30, 21);

        jRadioButton134.setEnabled(false);
        getContentPane().add(jRadioButton134);
        jRadioButton134.setBounds(290, 420, 30, 21);

        jRadioButton135.setEnabled(false);
        getContentPane().add(jRadioButton135);
        jRadioButton135.setBounds(320, 420, 30, 21);

        jRadioButton136.setEnabled(false);
        getContentPane().add(jRadioButton136);
        jRadioButton136.setBounds(610, 70, 30, 21);

        jRadioButton137.setEnabled(false);
        getContentPane().add(jRadioButton137);
        jRadioButton137.setBounds(640, 70, 30, 21);

        jRadioButton138.setEnabled(false);
        getContentPane().add(jRadioButton138);
        jRadioButton138.setBounds(640, 90, 30, 21);

        jRadioButton139.setEnabled(false);
        getContentPane().add(jRadioButton139);
        jRadioButton139.setBounds(610, 90, 30, 21);

        jRadioButton140.setEnabled(false);
        getContentPane().add(jRadioButton140);
        jRadioButton140.setBounds(610, 110, 30, 21);

        jRadioButton141.setEnabled(false);
        getContentPane().add(jRadioButton141);
        jRadioButton141.setBounds(640, 110, 30, 21);

        jRadioButton142.setEnabled(false);
        getContentPane().add(jRadioButton142);
        jRadioButton142.setBounds(640, 130, 30, 21);

        jRadioButton143.setEnabled(false);
        getContentPane().add(jRadioButton143);
        jRadioButton143.setBounds(610, 130, 30, 21);

        jRadioButton30.setEnabled(false);
        getContentPane().add(jRadioButton30);
        jRadioButton30.setBounds(610, 150, 30, 21);

        jRadioButton31.setEnabled(false);
        getContentPane().add(jRadioButton31);
        jRadioButton31.setBounds(640, 150, 30, 21);

        jLabel46.setText("DEF");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(640, 50, 30, 14);

        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("OK");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(610, 50, 20, 14);

        buttonGroup23.add(OkAssento);
        OkAssento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkAssentoActionPerformed(evt);
            }
        });
        getContentPane().add(OkAssento);
        OkAssento.setBounds(640, 240, 30, 21);

        buttonGroup23.add(DefAssento);
        DefAssento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefAssentoActionPerformed(evt);
            }
        });
        getContentPane().add(DefAssento);
        DefAssento.setBounds(670, 240, 30, 21);

        jRadioButton144.setEnabled(false);
        getContentPane().add(jRadioButton144);
        jRadioButton144.setBounds(720, 240, 30, 21);

        jRadioButton145.setEnabled(false);
        getContentPane().add(jRadioButton145);
        jRadioButton145.setBounds(750, 240, 30, 21);

        buttonGroup24.add(OkCadeirinha);
        OkCadeirinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkCadeirinhaActionPerformed(evt);
            }
        });
        getContentPane().add(OkCadeirinha);
        OkCadeirinha.setBounds(640, 280, 30, 21);

        buttonGroup24.add(DefCadeirinha);
        DefCadeirinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefCadeirinhaActionPerformed(evt);
            }
        });
        getContentPane().add(DefCadeirinha);
        DefCadeirinha.setBounds(670, 280, 30, 21);

        jRadioButton146.setEnabled(false);
        getContentPane().add(jRadioButton146);
        jRadioButton146.setBounds(720, 280, 30, 21);

        jRadioButton147.setEnabled(false);
        getContentPane().add(jRadioButton147);
        jRadioButton147.setBounds(750, 280, 30, 21);

        buttonGroup25.add(OkBebe);
        OkBebe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkBebeActionPerformed(evt);
            }
        });
        getContentPane().add(OkBebe);
        OkBebe.setBounds(640, 320, 30, 21);

        buttonGroup25.add(DefBebe);
        DefBebe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefBebeActionPerformed(evt);
            }
        });
        getContentPane().add(DefBebe);
        DefBebe.setBounds(670, 320, 30, 21);

        jRadioButton148.setEnabled(false);
        getContentPane().add(jRadioButton148);
        jRadioButton148.setBounds(720, 320, 30, 21);

        jRadioButton149.setEnabled(false);
        getContentPane().add(jRadioButton149);
        jRadioButton149.setBounds(750, 320, 30, 21);

        buttonGroup26.add(OkGPS);
        OkGPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkGPSActionPerformed(evt);
            }
        });
        getContentPane().add(OkGPS);
        OkGPS.setBounds(640, 360, 30, 21);

        buttonGroup26.add(DefGPS);
        DefGPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefGPSActionPerformed(evt);
            }
        });
        getContentPane().add(DefGPS);
        DefGPS.setBounds(670, 360, 30, 21);

        jRadioButton150.setEnabled(false);
        getContentPane().add(jRadioButton150);
        jRadioButton150.setBounds(720, 360, 30, 21);

        jRadioButton151.setEnabled(false);
        getContentPane().add(jRadioButton151);
        jRadioButton151.setBounds(750, 360, 30, 21);

        buttonGroup27.add(OkWifi);
        OkWifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkWifiActionPerformed(evt);
            }
        });
        getContentPane().add(OkWifi);
        OkWifi.setBounds(640, 400, 30, 21);

        buttonGroup27.add(DefWifi);
        DefWifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefWifiActionPerformed(evt);
            }
        });
        getContentPane().add(DefWifi);
        DefWifi.setBounds(670, 400, 30, 21);

        jRadioButton152.setEnabled(false);
        getContentPane().add(jRadioButton152);
        jRadioButton152.setBounds(720, 400, 30, 21);

        jRadioButton153.setEnabled(false);
        getContentPane().add(jRadioButton153);
        jRadioButton153.setBounds(750, 400, 30, 21);

        buttonGroup28.add(OkKit);
        OkKit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkKitActionPerformed(evt);
            }
        });
        getContentPane().add(OkKit);
        OkKit.setBounds(640, 430, 30, 21);

        buttonGroup28.add(DefKit);
        DefKit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefKitActionPerformed(evt);
            }
        });
        getContentPane().add(DefKit);
        DefKit.setBounds(670, 430, 30, 21);

        jRadioButton154.setEnabled(false);
        getContentPane().add(jRadioButton154);
        jRadioButton154.setBounds(720, 430, 30, 21);

        jRadioButton155.setEnabled(false);
        getContentPane().add(jRadioButton155);
        jRadioButton155.setBounds(750, 430, 30, 21);

        jLabel48.setText("DEF");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(750, 220, 30, 14);

        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("OK");
        getContentPane().add(jLabel49);
        jLabel49.setBounds(720, 220, 20, 14);

        jLabel50.setText("DEF");
        getContentPane().add(jLabel50);
        jLabel50.setBounds(670, 220, 30, 14);

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("OK");
        getContentPane().add(jLabel51);
        jLabel51.setBounds(640, 220, 20, 14);

        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("Antes");
        getContentPane().add(jLabel52);
        jLabel52.setBounds(210, 60, 50, 14);

        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Depois");
        getContentPane().add(jLabel53);
        jLabel53.setBounds(290, 60, 50, 14);

        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Depois");
        getContentPane().add(jLabel54);
        jLabel54.setBounds(610, 30, 50, 14);

        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Antes");
        getContentPane().add(jLabel55);
        jLabel55.setBounds(530, 30, 50, 14);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 470, 63, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo800500.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OkRetrovisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkRetrovisorActionPerformed
       
    }//GEN-LAST:event_OkRetrovisorActionPerformed

    private void OkFarolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkFarolActionPerformed
       
    }//GEN-LAST:event_OkFarolActionPerformed

    private void DefFarolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefFarolActionPerformed
       
    }//GEN-LAST:event_DefFarolActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int resposta = JOptionPane.showConfirmDialog(null, "Esta operação irá Salvar valores na base de dados!\n\nDeseja continuar?", "Aviso", JOptionPane.YES_NO_OPTION);
        
        if(resposta == JOptionPane.YES_OPTION){
            try{
                Checklist chk = new Checklist();
                if (this.OkRetrovisor.isSelected()) {
                    chk.setRetrovisor_checklist("OK");
               }
               if (this.DefRetrovisor.isSelected()) {
                  chk.setRetrovisor_checklist("DEF");
               }
               if (this.OkFarol.isSelected()) {
                    chk.setFarol_checklist("OK");
               }
               if (this.DefFarol.isSelected()) {
                   chk.setFarol_checklist("DEF"); 
                   
               }if (this.OkLanterna.isSelected()) {
                    chk.setLanternas_checklist("OK");
               }
               if (this.DefLanterna.isSelected()) {
                  chk.setLanternas_checklist("DEF");
               }
               if (this.OkLuz1.isSelected()) {
                    chk.setLuzFreio_checklist("OK");
               }
               if (this.DefLuz1.isSelected()) {
                  chk.setLuzFreio_checklist("DEF");
               }
               if (this.OkLuz2.isSelected()) {
                    chk.setLuzRe_checklist("OK");
               }
               if (this.DefLuz2.isSelected()) {
                  chk.setLuzRe_checklist("DEF");
               }
               if (this.OkSetas.isSelected()) {
                    chk.setSetas_checklist("OK");
               }
               if (this.DefSetas.isSelected()) {
                  chk.setSetas_checklist("DEF");
               }
               if (this.OkLuzTeto.isSelected()) {
                    chk.setLuzTeto_checklist("OK");
               }
               if (this.DefLuzTeto.isSelected()) {
                  chk.setLuzTeto_checklist("DEF");
               }
              if (this.OkAr.isSelected()) {
                    chk.setArCondicionado_checklist("OK");
               }
               if (this.DefAr.isSelected()) {
                  chk.setArCondicionado_checklist("DEF");
               }
               if (this.OkPart.isSelected()) {
                    chk.setPartida_checklist("OK");
               }
               if (this.DefPart.isSelected()) {
                  chk.setPartida_checklist("DEF");
               }
               if (this.Okteto.isSelected()) {
                    chk.setTeto_checklist("OK");
               }
               if (this.DefTeto.isSelected()) {
                  chk.setTeto_checklist("DEF");
               }
               if (this.OkLimpador.isSelected()) {
                    chk.setLimpadores_checklist("OK");
               }
               if (this.DefLimpador.isSelected()) {
                  chk.setLimpadores_checklist("DEF");
               }
               if (this.OkSens.isSelected()) {
                    chk.setSensor_checklist("OK");
               }
               if (this.DefSens.isSelected()) {
                  chk.setSensor_checklist("DEF");
               }
               if (this.OkRelogio.isSelected()) {
                    chk.setRelogio_checklist("OK");
               }
               if (this.DefRelogio.isSelected()) {
                  chk.setRelogio_checklist("DEF");
               }
               if (this.OkAlarme.isSelected()) {
                    chk.setAlarme_checklist("OK");
               }
               if (this.DefAlarme.isSelected()) {
                  chk.setAlarme_checklist("DEF");
               }
               
               if (this.OkTravas.isSelected()) {
                    chk.setTravas_checklist("OK");
               }
               if (this.DefTravas.isSelected()) {
                   chk.setTravas_checklist("DEF");
               }
               if (this.OkTampa.isSelected()) {
                    chk.setTampaPortaLuv_checklist("OK");
               }
               if (this.DefTampa.isSelected()) {
                  chk.setTampaPortaLuv_checklist("DEF");
               }
               if (this.OkPisca.isSelected()) {
                    chk.setPiscaAlerta_checklist("OK");
               }
               if (this.DefPisca.isSelected()) {
                  chk.setPiscaAlerta_checklist("DEF");
               }
               if (this.OkAcendedor.isSelected()) {
                    chk.setAcendedor_checklist("OK");
               }
               if (this.DefAcendedor.isSelected()) {
                  chk.setAcendedor_checklist("DEF");
               }
               if (this.OkRadio.isSelected()) {
                    chk.setRadio_checklist("OK");
               }
               if (this.DefRadio.isSelected()) {
                  chk.setRadio_checklist("DEF");
               }
               if (this.OkVidro.isSelected()) {
                    chk.setVidroElet_checklist("OK");
               }
               if (this.DefVidro.isSelected()) {
                  chk.setVidroElet_checklist("DEF");
               }
               if (this.OkBateria.isSelected()) {
                    chk.setBateria_checklist("OK");
               }
               if (this.DefBateria.isSelected()) {
                  chk.setBateria_checklist("DEF");
               }
               if (this.OkBuzina.isSelected()) {
                    chk.setBuzina_checklist("OK");
               }
               if (this.Defbuzina.isSelected()) {
                  chk.setBuzina_checklist("DEF");
               }
               if (this.OkAssento.isSelected()) {
                    chk.setAssentoElevADC_checklist("OK");
               }
               if (this.DefAssento.isSelected()) {
                  chk.setAssentoElevADC_checklist("DEF");
               }
               if (this.OkCadeirinha.isSelected()) {
                    chk.setCadeirinhaADC_checklist("OK");
               }
               if (this.DefCadeirinha.isSelected()) {
                  chk.setCadeirinhaADC_checklist("DEF");
               }
               if (this.OkBebe.isSelected()) {
                    chk.setBebeConfADC_checklist("OK");
               }
               if (this.DefBebe.isSelected()) {
                  chk.setBebeConfADC_checklist("DEF");
               }
               if (this.OkGPS.isSelected()) {
                    chk.setGpsADC_checklist("OK");
               }
               if (this.DefGPS.isSelected()) {
                  chk.setGpsADC_checklist("DEF");
               }
               if (this.OkWifi.isSelected()) {
                    chk.setWifiADC_checklist("OK");
               }
               if (this.DefWifi.isSelected()) {
                  chk.setWifiADC_checklist("DEF");
               }
               if (this.OkKit.isSelected()) {
                    chk.setKitConnecADC_checklist("OK");
               }
               if (this.DefKit.isSelected()) {
                  chk.setKitConnecADC_checklist("DEF");
               }
                ChecklistDAO dao = new ChecklistDAO();
                dao.salvar(chk);
                JOptionPane.showMessageDialog(null, "Dados salvos com sucesso");
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        }
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void OkLanternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkLanternaActionPerformed
       
    }//GEN-LAST:event_OkLanternaActionPerformed

    private void DefLanternaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefLanternaActionPerformed
        
    }//GEN-LAST:event_DefLanternaActionPerformed

    private void DefRetrovisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefRetrovisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefRetrovisorActionPerformed

    private void OkLuz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkLuz1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkLuz1ActionPerformed

    private void DefLuz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefLuz1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefLuz1ActionPerformed

    private void OkLuz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkLuz2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkLuz2ActionPerformed

    private void DefLuz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefLuz2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefLuz2ActionPerformed

    private void OkSetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkSetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkSetasActionPerformed

    private void DefSetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefSetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefSetasActionPerformed

    private void OkLuzTetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkLuzTetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkLuzTetoActionPerformed

    private void DefLuzTetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefLuzTetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefLuzTetoActionPerformed

    private void OkArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkArActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkArActionPerformed

    private void DefArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefArActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefArActionPerformed

    private void OkPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkPartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkPartActionPerformed

    private void DefPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefPartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefPartActionPerformed

    private void OktetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OktetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OktetoActionPerformed

    private void DefTetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefTetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefTetoActionPerformed

    private void OkLimpadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkLimpadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkLimpadorActionPerformed

    private void DefLimpadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefLimpadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefLimpadorActionPerformed

    private void OkRelogioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkRelogioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkRelogioActionPerformed

    private void DefRelogioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefRelogioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefRelogioActionPerformed

    private void OkAlarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkAlarmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkAlarmeActionPerformed

    private void DefAlarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefAlarmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefAlarmeActionPerformed

    private void OkTravasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkTravasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkTravasActionPerformed

    private void DefTravasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefTravasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefTravasActionPerformed

    private void OkTampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkTampaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkTampaActionPerformed

    private void DefTampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefTampaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefTampaActionPerformed

    private void OkPiscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkPiscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkPiscaActionPerformed

    private void DefPiscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefPiscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefPiscaActionPerformed

    private void OkAcendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkAcendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkAcendedorActionPerformed

    private void DefAcendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefAcendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefAcendedorActionPerformed

    private void OkSensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkSensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkSensActionPerformed

    private void DefSensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefSensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefSensActionPerformed

    private void OkRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkRadioActionPerformed

    private void DefRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefRadioActionPerformed

    private void OkVidroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkVidroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkVidroActionPerformed

    private void DefVidroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefVidroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefVidroActionPerformed

    private void OkBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkBateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkBateriaActionPerformed

    private void DefBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefBateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefBateriaActionPerformed

    private void OkBuzinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkBuzinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkBuzinaActionPerformed

    private void DefbuzinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefbuzinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefbuzinaActionPerformed

    private void OkAssentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkAssentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkAssentoActionPerformed

    private void DefAssentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefAssentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefAssentoActionPerformed

    private void OkCadeirinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkCadeirinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkCadeirinhaActionPerformed

    private void DefCadeirinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefCadeirinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefCadeirinhaActionPerformed

    private void OkBebeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkBebeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkBebeActionPerformed

    private void DefBebeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefBebeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefBebeActionPerformed

    private void OkGPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkGPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkGPSActionPerformed

    private void DefGPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefGPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefGPSActionPerformed

    private void OkWifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkWifiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkWifiActionPerformed

    private void DefWifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefWifiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefWifiActionPerformed

    private void OkKitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkKitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OkKitActionPerformed

    private void DefKitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefKitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DefKitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCheckList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCheckList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCheckList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCheckList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCheckList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DefAcendedor;
    private javax.swing.JRadioButton DefAlarme;
    private javax.swing.JRadioButton DefAr;
    private javax.swing.JRadioButton DefAssento;
    private javax.swing.JRadioButton DefBateria;
    private javax.swing.JRadioButton DefBebe;
    private javax.swing.JRadioButton DefCadeirinha;
    private javax.swing.JRadioButton DefFarol;
    private javax.swing.JRadioButton DefGPS;
    private javax.swing.JRadioButton DefKit;
    private javax.swing.JRadioButton DefLanterna;
    private javax.swing.JRadioButton DefLimpador;
    private javax.swing.JRadioButton DefLuz1;
    private javax.swing.JRadioButton DefLuz2;
    private javax.swing.JRadioButton DefLuzTeto;
    private javax.swing.JRadioButton DefPart;
    private javax.swing.JRadioButton DefPisca;
    private javax.swing.JRadioButton DefRadio;
    private javax.swing.JRadioButton DefRelogio;
    private javax.swing.JRadioButton DefRetrovisor;
    private javax.swing.JRadioButton DefSens;
    private javax.swing.JRadioButton DefSetas;
    private javax.swing.JRadioButton DefTampa;
    private javax.swing.JRadioButton DefTeto;
    private javax.swing.JRadioButton DefTravas;
    private javax.swing.JRadioButton DefVidro;
    private javax.swing.JRadioButton DefWifi;
    private javax.swing.JRadioButton Defbuzina;
    private javax.swing.JRadioButton OkAcendedor;
    private javax.swing.JRadioButton OkAlarme;
    private javax.swing.JRadioButton OkAr;
    private javax.swing.JRadioButton OkAssento;
    private javax.swing.JRadioButton OkBateria;
    private javax.swing.JRadioButton OkBebe;
    private javax.swing.JRadioButton OkBuzina;
    private javax.swing.JRadioButton OkCadeirinha;
    private javax.swing.JRadioButton OkFarol;
    private javax.swing.JRadioButton OkGPS;
    private javax.swing.JRadioButton OkKit;
    private javax.swing.JRadioButton OkLanterna;
    private javax.swing.JRadioButton OkLimpador;
    private javax.swing.JRadioButton OkLuz1;
    private javax.swing.JRadioButton OkLuz2;
    private javax.swing.JRadioButton OkLuzTeto;
    private javax.swing.JRadioButton OkPart;
    private javax.swing.JRadioButton OkPisca;
    private javax.swing.JRadioButton OkRadio;
    private javax.swing.JRadioButton OkRelogio;
    private javax.swing.JRadioButton OkRetrovisor;
    private javax.swing.JRadioButton OkSens;
    private javax.swing.JRadioButton OkSetas;
    private javax.swing.JRadioButton OkTampa;
    private javax.swing.JRadioButton OkTravas;
    private javax.swing.JRadioButton OkVidro;
    private javax.swing.JRadioButton OkWifi;
    private javax.swing.JRadioButton Okteto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup20;
    private javax.swing.ButtonGroup buttonGroup21;
    private javax.swing.ButtonGroup buttonGroup22;
    private javax.swing.ButtonGroup buttonGroup23;
    private javax.swing.ButtonGroup buttonGroup24;
    private javax.swing.ButtonGroup buttonGroup25;
    private javax.swing.ButtonGroup buttonGroup26;
    private javax.swing.ButtonGroup buttonGroup27;
    private javax.swing.ButtonGroup buttonGroup28;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton104;
    private javax.swing.JRadioButton jRadioButton105;
    private javax.swing.JRadioButton jRadioButton106;
    private javax.swing.JRadioButton jRadioButton107;
    private javax.swing.JRadioButton jRadioButton108;
    private javax.swing.JRadioButton jRadioButton109;
    private javax.swing.JRadioButton jRadioButton110;
    private javax.swing.JRadioButton jRadioButton111;
    private javax.swing.JRadioButton jRadioButton112;
    private javax.swing.JRadioButton jRadioButton113;
    private javax.swing.JRadioButton jRadioButton114;
    private javax.swing.JRadioButton jRadioButton115;
    private javax.swing.JRadioButton jRadioButton116;
    private javax.swing.JRadioButton jRadioButton117;
    private javax.swing.JRadioButton jRadioButton118;
    private javax.swing.JRadioButton jRadioButton119;
    private javax.swing.JRadioButton jRadioButton120;
    private javax.swing.JRadioButton jRadioButton121;
    private javax.swing.JRadioButton jRadioButton122;
    private javax.swing.JRadioButton jRadioButton123;
    private javax.swing.JRadioButton jRadioButton124;
    private javax.swing.JRadioButton jRadioButton125;
    private javax.swing.JRadioButton jRadioButton126;
    private javax.swing.JRadioButton jRadioButton127;
    private javax.swing.JRadioButton jRadioButton128;
    private javax.swing.JRadioButton jRadioButton129;
    private javax.swing.JRadioButton jRadioButton130;
    private javax.swing.JRadioButton jRadioButton131;
    private javax.swing.JRadioButton jRadioButton132;
    private javax.swing.JRadioButton jRadioButton133;
    private javax.swing.JRadioButton jRadioButton134;
    private javax.swing.JRadioButton jRadioButton135;
    private javax.swing.JRadioButton jRadioButton136;
    private javax.swing.JRadioButton jRadioButton137;
    private javax.swing.JRadioButton jRadioButton138;
    private javax.swing.JRadioButton jRadioButton139;
    private javax.swing.JRadioButton jRadioButton140;
    private javax.swing.JRadioButton jRadioButton141;
    private javax.swing.JRadioButton jRadioButton142;
    private javax.swing.JRadioButton jRadioButton143;
    private javax.swing.JRadioButton jRadioButton144;
    private javax.swing.JRadioButton jRadioButton145;
    private javax.swing.JRadioButton jRadioButton146;
    private javax.swing.JRadioButton jRadioButton147;
    private javax.swing.JRadioButton jRadioButton148;
    private javax.swing.JRadioButton jRadioButton149;
    private javax.swing.JRadioButton jRadioButton150;
    private javax.swing.JRadioButton jRadioButton151;
    private javax.swing.JRadioButton jRadioButton152;
    private javax.swing.JRadioButton jRadioButton153;
    private javax.swing.JRadioButton jRadioButton154;
    private javax.swing.JRadioButton jRadioButton155;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    // End of variables declaration//GEN-END:variables
private String OK;
private String DEF;

}
