/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author konno
 */
public class TelaGerente extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerente
     */
    public TelaGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAlocar = new javax.swing.JLabel();
        jLabelBiell = new javax.swing.JLabel();
        jButtonVeiculosGerente = new javax.swing.JButton();
        jButtonRelatorioGerente = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelAlocar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alocar.png"))); // NOI18N
        getContentPane().add(jLabelAlocar);
        jLabelAlocar.setBounds(200, 30, 260, 80);

        jLabelBiell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/biell.png"))); // NOI18N
        getContentPane().add(jLabelBiell);
        jLabelBiell.setBounds(220, 330, 230, 110);

        jButtonVeiculosGerente.setBackground(new java.awt.Color(255, 0, 0));
        jButtonVeiculosGerente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVeiculosGerente.setText("Veículos");
        jButtonVeiculosGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeiculosGerenteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVeiculosGerente);
        jButtonVeiculosGerente.setBounds(210, 140, 230, 70);

        jButtonRelatorioGerente.setBackground(new java.awt.Color(255, 0, 0));
        jButtonRelatorioGerente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRelatorioGerente.setText("Relatórios");
        jButtonRelatorioGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioGerenteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelatorioGerente);
        jButtonRelatorioGerente.setBounds(210, 240, 230, 70);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 659, 433);

        setSize(new java.awt.Dimension(675, 472));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVeiculosGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeiculosGerenteActionPerformed
        try {
            TelaVeiculos tela = new TelaVeiculos();
            tela.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TelaGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonVeiculosGerenteActionPerformed

    private void jButtonRelatorioGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioGerenteActionPerformed
        try {
            TelaRelatorio tela = new TelaRelatorio();
            tela.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TelaGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRelatorioGerenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRelatorioGerente;
    private javax.swing.JButton jButtonVeiculosGerente;
    private javax.swing.JLabel jLabelAlocar;
    private javax.swing.JLabel jLabelBiell;
    private javax.swing.JLabel jLabelFundo;
    // End of variables declaration//GEN-END:variables
}
