/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.bean.Cliente;
import model.dao.ClienteDAO;

/**
 *
 * @author konno
 */
public class TelaClientesInserir extends javax.swing.JFrame {

    public TelaClientesInserir() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AltNomeCliente = new javax.swing.JLabel();
        AltCPFCliente = new javax.swing.JLabel();
        AltRGCliente = new javax.swing.JLabel();
        AltTelefoneCliente = new javax.swing.JLabel();
        AltTelefone2Cliente = new javax.swing.JLabel();
        AltEmailCliente = new javax.swing.JLabel();
        AltEnderecoCliente = new javax.swing.JLabel();
        AltBairroCliente = new javax.swing.JLabel();
        AltCidadeCliente = new javax.swing.JLabel();
        AltUFCliente = new javax.swing.JLabel();
        AltCEPCliente = new javax.swing.JLabel();
        AltNumCliente = new javax.swing.JLabel();
        AltValCliente = new javax.swing.JLabel();
        AltCatCliente = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCPF = new javax.swing.JTextField();
        jTextFieldRG = new javax.swing.JTextField();
        jTextFieldSMS = new javax.swing.JTextField();
        jTextFieldtel2 = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldUF = new javax.swing.JTextField();
        jTextFieldCEP = new javax.swing.JTextField();
        jTextFieldNCNH = new javax.swing.JTextField();
        jFormattedTextFieldValidade = new javax.swing.JFormattedTextField();
        jTextFieldCategoria = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        javax.swing.JLabel jLabelFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        AltNomeCliente.setText("Nome:");
        getContentPane().add(AltNomeCliente);
        AltNomeCliente.setBounds(40, 130, 40, 20);

        AltCPFCliente.setText("CPF:");
        getContentPane().add(AltCPFCliente);
        AltCPFCliente.setBounds(360, 130, 40, 20);

        AltRGCliente.setText("RG:");
        getContentPane().add(AltRGCliente);
        AltRGCliente.setBounds(570, 130, 30, 20);

        AltTelefoneCliente.setText("Telefone(SMS):");
        getContentPane().add(AltTelefoneCliente);
        AltTelefoneCliente.setBounds(40, 200, 100, 20);

        AltTelefone2Cliente.setText("Telefone2:");
        getContentPane().add(AltTelefone2Cliente);
        AltTelefone2Cliente.setBounds(260, 200, 80, 20);

        AltEmailCliente.setText("Email:");
        getContentPane().add(AltEmailCliente);
        AltEmailCliente.setBounds(460, 200, 40, 20);

        AltEnderecoCliente.setText("Endereço:");
        getContentPane().add(AltEnderecoCliente);
        AltEnderecoCliente.setBounds(40, 270, 70, 20);

        AltBairroCliente.setText("Bairro:");
        getContentPane().add(AltBairroCliente);
        AltBairroCliente.setBounds(350, 270, 50, 20);

        AltCidadeCliente.setText("Cidade:");
        getContentPane().add(AltCidadeCliente);
        AltCidadeCliente.setBounds(540, 270, 60, 20);

        AltUFCliente.setText("UF:");
        getContentPane().add(AltUFCliente);
        AltUFCliente.setBounds(690, 200, 20, 20);

        AltCEPCliente.setText("CEP:");
        getContentPane().add(AltCEPCliente);
        AltCEPCliente.setBounds(40, 340, 130, 20);

        AltNumCliente.setText("Número CNH:");
        getContentPane().add(AltNumCliente);
        AltNumCliente.setBounds(200, 340, 70, 20);

        AltValCliente.setText("Validade:");
        getContentPane().add(AltValCliente);
        AltValCliente.setBounds(390, 340, 44, 20);

        AltCatCliente.setText("Categoria:");
        getContentPane().add(AltCatCliente);
        AltCatCliente.setBounds(570, 340, 70, 20);

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(40, 150, 300, 30);
        getContentPane().add(jTextFieldCPF);
        jTextFieldCPF.setBounds(360, 150, 180, 30);
        getContentPane().add(jTextFieldRG);
        jTextFieldRG.setBounds(570, 150, 190, 30);
        getContentPane().add(jTextFieldSMS);
        jTextFieldSMS.setBounds(40, 220, 190, 30);
        getContentPane().add(jTextFieldtel2);
        jTextFieldtel2.setBounds(260, 220, 170, 30);
        getContentPane().add(jTextFieldEmail);
        jTextFieldEmail.setBounds(460, 220, 210, 30);

        jTextFieldEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEndereco);
        jTextFieldEndereco.setBounds(40, 290, 280, 30);

        jTextFieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldBairro);
        jTextFieldBairro.setBounds(350, 290, 150, 30);
        getContentPane().add(jTextFieldCidade);
        jTextFieldCidade.setBounds(540, 290, 180, 30);
        getContentPane().add(jTextFieldUF);
        jTextFieldUF.setBounds(690, 220, 80, 30);
        getContentPane().add(jTextFieldCEP);
        jTextFieldCEP.setBounds(40, 360, 130, 30);

        jTextFieldNCNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNCNHActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNCNH);
        jTextFieldNCNH.setBounds(200, 360, 160, 30);

        jFormattedTextFieldValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldValidadeActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldValidade);
        jFormattedTextFieldValidade.setBounds(390, 360, 150, 30);

        jTextFieldCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCategoria);
        jTextFieldCategoria.setBounds(570, 360, 110, 30);

        btnInserir.setBackground(new java.awt.Color(255, 0, 0));
        btnInserir.setForeground(new java.awt.Color(255, 255, 255));
        btnInserir.setText("Adicionar");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        getContentPane().add(btnInserir);
        btnInserir.setBounds(660, 440, 110, 40);

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(530, 440, 110, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem-Título-2.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(310, 40, 150, 50);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem-Título-3.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(320, 440, 140, 60);

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo800500.png"))); // NOI18N
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void  salvar() throws ParseException, ParseException, SQLException{
        try{
            Cliente cli = new Cliente();
            cli.setNomeCli(jTextFieldNome.getText());
            cli.setCpfCli(Long.parseLong(jTextFieldCPF.getText()));
            cli.setRgCli(jTextFieldRG.getText());
            cli.setTelefoneSMSCli(jTextFieldSMS.getText());
            cli.setTelefone2Cli(jTextFieldtel2.getText());
            cli.setEmailCli(jTextFieldEmail.getText());
            cli.setEnderecoCli(jTextFieldEndereco.getText());
            cli.setBairroCli(jTextFieldBairro.getText());
            cli.setCidadeCli(jTextFieldCidade.getText());
            cli.setUfCli(jTextFieldUF.getText());
            cli.setCepCli(jTextFieldCEP.getText());
            cli.setNumeroCNHCli(jTextFieldNCNH.getText());
            //String[] dataSep = (jFormattedTextFieldValidade.getText()).split("/");
            //LocalDate data = LocalDate.of(Integer.parseInt(dataSep[2]), Integer.parseInt(dataSep[1]), Integer.parseInt(dataSep[0]));
            SimpleDateFormat formato = new SimpleDateFormat("YYYY-MM-DD");
            String data = jFormattedTextFieldValidade.getText();
            Date parseData =  formato.parse(data);
            cli.setValidadeCNHCli((java.sql.Date) parseData);
            cli.setCategoriaCli(jTextFieldCategoria.getText());

            ClienteDAO dao = new ClienteDAO();
            dao.novo(cli);
            JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!\n\n");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Erro ao salvar dados\n\n" + e);
        }
    }
     boolean verificavazio(){
         return (!jTextFieldNome.getText().equals("") || !jTextFieldCPF.getText().equals("")
                || !jTextFieldRG.getText().equals("") || !jTextFieldtel2.getText().equals("")
                || !jTextFieldEmail.getText().equals("") || !jTextFieldSMS.getText().equals("")
                || !jTextFieldEndereco.getText().equals("") || !jTextFieldBairro.getText().equals("")
                || !jTextFieldCidade.getText().equals("") || !jTextFieldUF.getText().equals("")
                || !jTextFieldCEP.getText().equals("") || !jTextFieldNCNH.getText().equals("")
                || !jFormattedTextFieldValidade.getText().equals("") || !jTextFieldCategoria.getText().equals(""));
     }       
             
      boolean verificaCPF(){
           // String strCpf;
              int     d1, d2;
	      int     digito1, digito2, resto;
	      int     digitoCPF;
	      String  nDigResult;
              
              

	      d1 = d2 = 0;
	      digito1 = digito2 = resto = 0;

	      for (int nCount = 1; nCount < jTextFieldCPF.getText().length() -1; nCount++)
	      {
	         digitoCPF = Integer.parseInt(jTextFieldCPF.getText().substring(nCount -1, nCount));

	         d1 = d1 + ( 11 - nCount ) * digitoCPF;

	         d2 = d2 + ( 12 - nCount ) * digitoCPF;
	      };

	      resto = (d1 % 11);

	      if (resto < 2)
	         digito1 = 0;
	      else
	         digito1 = 11 - resto;

	      d2 += 2 * digito1;

	      resto = (d2 % 11);

	      if (resto < 2)
	         digito2 = 0;
	      else
	         digito2 = 11 - resto;

	      String nDigVerific = jTextFieldCPF.getText().substring (jTextFieldCPF.getText().length()-2, jTextFieldCPF.getText().length());

	      nDigResult = String.valueOf(digito1) + String.valueOf(digito2);
              return nDigVerific.equals(nDigResult);
    }     
 
    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jTextFieldCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCategoriaActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        if(!verificavazio()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos. ");
        }else{
            if(!verificaCPF()){
                JOptionPane.showMessageDialog(null, "CPF com numeração inválida.");
                jTextFieldCPF.setText("");
            }else{
               
                try {
                    salvar();
                    TelaVeiculos tela = new TelaVeiculos();
                    tela.setVisible(true);
                    dispose();
                    
                   
                   
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao salvar dados\n\n" + ex);
                } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null, "Erro ao salvar dados\n\n" + ex);
                }
                }
            }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void jTextFieldNCNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNCNHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNCNHActionPerformed

    private void jTextFieldEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoActionPerformed

    private void jTextFieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroActionPerformed

    private void jFormattedTextFieldValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldValidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientesInserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientesInserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientesInserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientesInserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientesInserir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AltBairroCliente;
    private javax.swing.JLabel AltCEPCliente;
    private javax.swing.JLabel AltCPFCliente;
    private javax.swing.JLabel AltCatCliente;
    private javax.swing.JLabel AltCidadeCliente;
    private javax.swing.JLabel AltEmailCliente;
    private javax.swing.JLabel AltEnderecoCliente;
    private javax.swing.JLabel AltNomeCliente;
    private javax.swing.JLabel AltNumCliente;
    private javax.swing.JLabel AltRGCliente;
    private javax.swing.JLabel AltTelefone2Cliente;
    private javax.swing.JLabel AltTelefoneCliente;
    private javax.swing.JLabel AltUFCliente;
    private javax.swing.JLabel AltValCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JFormattedTextField jFormattedTextFieldValidade;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCEP;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNCNH;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldRG;
    private javax.swing.JTextField jTextFieldSMS;
    private javax.swing.JTextField jTextFieldUF;
    private javax.swing.JTextField jTextFieldtel2;
    // End of variables declaration//GEN-END:variables


    

}
