/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.dao.AtendenteDAO;
import model.dao.GerenteDAO;
/**
 *
 * @author konno
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuarioLogin = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenhaLogin = new javax.swing.JPasswordField();
        jButtonAtendente = new javax.swing.JButton();
        jButtonGerente = new javax.swing.JButton();
        javax.swing.JLabel jLabelFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/biell.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 340, 210, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alocar.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 30, 280, 80);

        jLabelUsuario.setText("Usuário:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(200, 150, 70, 30);

        jTextFieldUsuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuarioLogin);
        jTextFieldUsuarioLogin.setBounds(250, 150, 200, 30);

        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(200, 210, 50, 30);
        getContentPane().add(jPasswordFieldSenhaLogin);
        jPasswordFieldSenhaLogin.setBounds(250, 210, 200, 30);

        jButtonAtendente.setBackground(new java.awt.Color(255, 0, 0));
        jButtonAtendente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtendente.setText("Atendente");
        jButtonAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtendenteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtendente);
        jButtonAtendente.setBounds(190, 280, 140, 30);

        jButtonGerente.setBackground(new java.awt.Color(255, 0, 0));
        jButtonGerente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGerente.setText("Gerente");
        jButtonGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGerente);
        jButtonGerente.setBounds(350, 280, 140, 30);

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(0, 0, 670, 414);

        setSize(new java.awt.Dimension(685, 453));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenteActionPerformed
         GerenteDAO dao = new GerenteDAO();
       
       if(dao.checkLogin(jTextFieldUsuarioLogin.getText(), jPasswordFieldSenhaLogin.getText())){
           TelaGerente tela = new TelaGerente();
           tela.setVisible(true);
           dispose();
       }else{
           JOptionPane.showMessageDialog(null, "Senha incorreta!");
       }

    }//GEN-LAST:event_jButtonGerenteActionPerformed

    private void jButtonAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtendenteActionPerformed
       AtendenteDAO dao = new AtendenteDAO();
       
       if(dao.checkLogin(jTextFieldUsuarioLogin.getText(), jPasswordFieldSenhaLogin.getText())){
           TelaAtendente tela = new TelaAtendente();
       tela.setVisible(true);
       dispose();
       }else{
           JOptionPane.showMessageDialog(null, "Senha incorreta!");
       }
 
    }//GEN-LAST:event_jButtonAtendenteActionPerformed

    private void jTextFieldUsuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtendente;
    private javax.swing.JButton jButtonGerente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordFieldSenhaLogin;
    private javax.swing.JTextField jTextFieldUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
