/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.bean.Cliente;
import model.dao.ClienteDAO;

/**
 *
 * @author konno
 */
public class TelaClientesAlterar extends javax.swing.JFrame {
    int flag =0;
    String cod_cliente;
    Cliente cli = new Cliente();
    ClienteDAO clientedao = new ClienteDAO();
    
    /**
     * Creates new form TelaClientesAlterar
     */
    public TelaClientesAlterar(String codigo) throws SQLException {
        initComponents();
        
        cod_cliente = codigo;
        int cod = Integer.parseInt(cod_cliente.trim());
        cli = clientedao.buscaCadastroPorCodigo(cod);
         
             jTextFieldNome.setText(cli.getNomeCli());
             TxtRg.setText(cli.getRgCli());
             TxtTelSMS.setText(cli.getTelefoneSMSCli());
             TxtTel2.setText(cli.getTelefone2Cli());
             TxtEmail.setText(cli.getEmailCli());
             TxtEnd.setText(cli.getEnderecoCli());
             TxtBairro.setText(cli.getBairroCli());
             TxtCidade.setText(cli.getCidadeCli());
             TxtUF.setText(cli.getUfCli());
             TxtCEP.setText(cli.getCepCli());
             TxtNumCNH.setText(cli.getNumeroCNHCli());
             Date dataAtual = new Date();
             DateFormat dateFormat;
            //dateFormat = new SimpleDateFormat(cli.getValidadeCNHCli());
             //String dataFormatada = dateFormat.format(dataAtual);
 
             //TxtValidade.setText(cli. getValidadeCNHCli());
             TxtCat.setText(cli.getCategoriaCli());
             txtid.setText(Integer.toString(cod));
             txtid.setEditable(false);
    }
    

    private TelaClientesAlterar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
   boolean verificaDados(){
        return (!jTextFieldNome.getText().equals("") 
                || !TxtRg.getText().equals("") || !TxtTel2.getText().equals("")
                || !TxtEmail.getText().equals("") || !TxtTelSMS.getText().equals("")
                || !TxtEnd.getText().equals("") || !TxtBairro.getText().equals("")
                || !TxtCidade.getText().equals("") || !TxtUF.getText().equals("")
                || !TxtCEP.getText().equals("") || !TxtNumCNH.getText().equals("")
                || !TxtValidade.getText().equals("") || !TxtCat.getText().equals(""));
                
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AltNomeCliente = new javax.swing.JLabel();
        AltCPFCliente = new javax.swing.JLabel();
        AltRGCliente = new javax.swing.JLabel();
        AltTelefoneCliente = new javax.swing.JLabel();
        AltTelefone2Cliente = new javax.swing.JLabel();
        AltEmailCliente = new javax.swing.JLabel();
        AltEnderecoCliente = new javax.swing.JLabel();
        AltBairroCliente = new javax.swing.JLabel();
        AltCidadeCliente = new javax.swing.JLabel();
        AltUFCliente = new javax.swing.JLabel();
        AltCEPCliente = new javax.swing.JLabel();
        AltNumCliente = new javax.swing.JLabel();
        AltValCliente = new javax.swing.JLabel();
        AltCatCliente = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        TxtCPF = new javax.swing.JTextField();
        TxtRg = new javax.swing.JTextField();
        TxtTelSMS = new javax.swing.JTextField();
        TxtTel2 = new javax.swing.JTextField();
        TxtEmail = new javax.swing.JTextField();
        TxtEnd = new javax.swing.JTextField();
        TxtBairro = new javax.swing.JTextField();
        TxtCidade = new javax.swing.JTextField();
        TxtUF = new javax.swing.JTextField();
        TxtCEP = new javax.swing.JTextField();
        TxtNumCNH = new javax.swing.JTextField();
        TxtValidade = new javax.swing.JFormattedTextField();
        TxtCat = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        lid = new javax.swing.JLabel();
        javax.swing.JLabel jLabelFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        AltNomeCliente.setText("Nome:");
        getContentPane().add(AltNomeCliente);
        AltNomeCliente.setBounds(40, 160, 280, 20);

        AltCPFCliente.setText("CPF:");
        getContentPane().add(AltCPFCliente);
        AltCPFCliente.setBounds(350, 160, 180, 20);

        AltRGCliente.setText("RG:");
        getContentPane().add(AltRGCliente);
        AltRGCliente.setBounds(570, 160, 180, 20);

        AltTelefoneCliente.setText("Telefone(SMS):");
        getContentPane().add(AltTelefoneCliente);
        AltTelefoneCliente.setBounds(40, 230, 180, 20);

        AltTelefone2Cliente.setText("Telefone2:");
        getContentPane().add(AltTelefone2Cliente);
        AltTelefone2Cliente.setBounds(250, 230, 170, 20);

        AltEmailCliente.setText("Email:");
        getContentPane().add(AltEmailCliente);
        AltEmailCliente.setBounds(450, 230, 210, 20);

        AltEnderecoCliente.setText("Endereço:");
        getContentPane().add(AltEnderecoCliente);
        AltEnderecoCliente.setBounds(40, 300, 280, 20);

        AltBairroCliente.setText("Bairro:");
        getContentPane().add(AltBairroCliente);
        AltBairroCliente.setBounds(350, 300, 140, 20);

        AltCidadeCliente.setText("Cidade:");
        getContentPane().add(AltCidadeCliente);
        AltCidadeCliente.setBounds(530, 300, 220, 20);

        AltUFCliente.setText("UF:");
        getContentPane().add(AltUFCliente);
        AltUFCliente.setBounds(680, 230, 80, 20);

        AltCEPCliente.setText("CEP:");
        getContentPane().add(AltCEPCliente);
        AltCEPCliente.setBounds(40, 370, 120, 20);

        AltNumCliente.setText("Numero CNH:");
        getContentPane().add(AltNumCliente);
        AltNumCliente.setBounds(210, 370, 160, 20);

        AltValCliente.setText("Validade:");
        getContentPane().add(AltValCliente);
        AltValCliente.setBounds(410, 370, 150, 20);

        AltCatCliente.setText("Categoria:");
        getContentPane().add(AltCatCliente);
        AltCatCliente.setBounds(590, 370, 110, 20);

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(40, 180, 280, 30);

        TxtCPF.setEnabled(false);
        getContentPane().add(TxtCPF);
        TxtCPF.setBounds(350, 180, 180, 30);

        TxtRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRgActionPerformed(evt);
            }
        });
        getContentPane().add(TxtRg);
        TxtRg.setBounds(570, 180, 180, 30);
        getContentPane().add(TxtTelSMS);
        TxtTelSMS.setBounds(40, 250, 180, 30);
        getContentPane().add(TxtTel2);
        TxtTel2.setBounds(250, 250, 170, 30);
        getContentPane().add(TxtEmail);
        TxtEmail.setBounds(450, 250, 210, 30);
        getContentPane().add(TxtEnd);
        TxtEnd.setBounds(40, 320, 280, 30);
        getContentPane().add(TxtBairro);
        TxtBairro.setBounds(350, 320, 140, 30);
        getContentPane().add(TxtCidade);
        TxtCidade.setBounds(530, 320, 220, 30);
        getContentPane().add(TxtUF);
        TxtUF.setBounds(680, 250, 70, 30);
        getContentPane().add(TxtCEP);
        TxtCEP.setBounds(40, 390, 130, 30);
        getContentPane().add(TxtNumCNH);
        TxtNumCNH.setBounds(210, 390, 160, 30);
        getContentPane().add(TxtValidade);
        TxtValidade.setBounds(410, 390, 150, 30);

        TxtCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCatActionPerformed(evt);
            }
        });
        getContentPane().add(TxtCat);
        TxtCat.setBounds(590, 390, 110, 30);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(670, 440, 110, 40);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 440, 110, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem-Título-2.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(310, 30, 190, 70);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sem-Título-3.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(340, 440, 140, 60);

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid);
        txtid.setBounds(40, 120, 110, 30);

        lid.setText("ID:");
        getContentPane().add(lid);
        lid.setBounds(40, 100, 110, 20);

        jLabelFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo800500.png"))); // NOI18N
        getContentPane().add(jLabelFundoLogin);
        jLabelFundoLogin.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(816, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxtRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRgActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        /*Cliente cli = new Cliente();
        if(flag==1){
            cli.setNomeCli(jTextFieldNome.getText());
            cli.setCpfCli(Long.parseLong(TxtCPF.getText()));
            cli.setRgCli(TxtRg.getText());
            cli.setTelefoneSMSCli(TxtTelSMS.getText());
            cli.setTelefone2Cli(TxtTel2.getText());
            cli.setEmailCli(TxtEmail.getText());
            cli.setEnderecoCli(TxtEnd.getText());
            cli.setBairroCli(TxtBairro.getText());
            cli.setCidadeCli(TxtCidade.getText());
            cli.setUfCli(TxtUF.getText());
            cli.setCepCli(TxtCEP.getText());
            cli.setNumeroCNHCli(TxtNumCNH.getText());
            ClienteDAO dao = new ClienteDAO();
            dao.novo(cli);
            
            jTextFieldNome.setText("");
        }else{
             cli.setNomeCli(jTextFieldNome.getText());
            cli.setCpfCli(Long.parseLong(TxtCPF.getText()));
            cli.setRgCli(TxtRg.getText());
            cli.setTelefoneSMSCli(TxtTelSMS.getText());
            cli.setTelefone2Cli(TxtTel2.getText());
            cli.setEmailCli(TxtEmail.getText());
            cli.setEnderecoCli(TxtEnd.getText());
            cli.setBairroCli(TxtBairro.getText());
            cli.setCidadeCli(TxtCidade.getText());
            cli.setUfCli(TxtUF.getText());
            cli.setCepCli(TxtCEP.getText());
            cli.setNumeroCNHCli(TxtNumCNH.getText());
            
            ClienteDAO dao = new ClienteDAO();
            try {
                dao.editar(cli);
            } catch (SQLException ex) {
                Logger.getLogger(TelaClientesAlterar.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        cli.setRgCli(TxtRg.getText());
            cli.setTelefoneSMSCli(TxtTelSMS.getText());
            cli.setTelefone2Cli(TxtTel2.getText());
            cli.setEmailCli(TxtEmail.getText());
            cli.setEnderecoCli(TxtEnd.getText());
            cli.setBairroCli(TxtBairro.getText());
            cli.setCidadeCli(TxtCidade.getText());
            cli.setUfCli(TxtUF.getText());
            cli.setCepCli(TxtCEP.getText());
            cli.setNumeroCNHCli(TxtNumCNH.getText());
        
        
        if(verificaDados()){
                     Cliente cli = new Cliente();
            
            cli.setNomeCli(jTextFieldNome.getText());
            
            ClienteDAO dao = new ClienteDAO();
            dao.novo(cli);
            JOptionPane.showMessageDialog(null,"Produto Alterado com sucesso!");
            }else{
            JOptionPane.showMessageDialog(null,"Campos não preenchidos!\nTodos os Campos são obrigatórios.", "Alerta", JOptionPane.WARNING_MESSAGE);
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Valore(s) inválido(s).\nERROR: "+e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }                                
        
        
        
        }*/
        int resposta = JOptionPane.showConfirmDialog(null, "Esta operação irá atualizar valores na base de dados!\n\nDeseja continuar?", "Aviso", JOptionPane.YES_NO_OPTION);
        
        if(resposta == JOptionPane.YES_OPTION){
            try{
                Cliente cli = new Cliente();
                cli.setNomeCli(jTextFieldNome.getText());
                //cli.setCpfCli(Long.parseLong(TxtCPF.getText()));
                cli.setRgCli(TxtRg.getText());
                cli.setTelefoneSMSCli(TxtTelSMS.getText());
                cli.setTelefone2Cli(TxtTel2.getText());
                cli.setEmailCli(TxtTel2.getText());
                cli.setEnderecoCli(TxtEnd.getText());
                cli.setBairroCli(TxtBairro.getText());
                cli.setCidadeCli(TxtCidade.getText());
                cli.setUfCli(TxtUF.getText());
                cli.setCepCli(TxtCEP.getText());
                cli.setNumeroCNHCli(TxtNumCNH.getText());
                //SimpleDateFormat formato = new SimpleDateFormat("YYYY-MM-DD");
                //String data = TxtValidade.getText();
                //Date parseData =  formato.parse(data);
                //cli.setValidadeCNHCli(parseData);
                cli.setCategoriaCli(TxtCat.getText());
                cli.setIdCli(Integer.parseInt(txtid.getText()));

                ClienteDAO dao = new ClienteDAO();
                dao.novo(cli);
                JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!\n\n");

                    TelaVeiculos tela = new TelaVeiculos();
                    tela.setVisible(true);
                    dispose();



            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Erro ao atualizar dados\n\n" + e);
            }
        }
            
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TxtCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCatActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientesAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientesAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientesAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientesAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaClientesAlterar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AltBairroCliente;
    private javax.swing.JLabel AltCEPCliente;
    private javax.swing.JLabel AltCPFCliente;
    private javax.swing.JLabel AltCatCliente;
    private javax.swing.JLabel AltCidadeCliente;
    private javax.swing.JLabel AltEmailCliente;
    private javax.swing.JLabel AltEnderecoCliente;
    private javax.swing.JLabel AltNomeCliente;
    private javax.swing.JLabel AltNumCliente;
    private javax.swing.JLabel AltRGCliente;
    private javax.swing.JLabel AltTelefone2Cliente;
    private javax.swing.JLabel AltTelefoneCliente;
    private javax.swing.JLabel AltUFCliente;
    private javax.swing.JLabel AltValCliente;
    private javax.swing.JTextField TxtBairro;
    private javax.swing.JTextField TxtCEP;
    private javax.swing.JTextField TxtCPF;
    private javax.swing.JTextField TxtCat;
    private javax.swing.JTextField TxtCidade;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtEnd;
    private javax.swing.JTextField TxtNumCNH;
    private javax.swing.JTextField TxtRg;
    private javax.swing.JTextField TxtTel2;
    private javax.swing.JTextField TxtTelSMS;
    private javax.swing.JTextField TxtUF;
    private javax.swing.JFormattedTextField TxtValidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JLabel lid;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables


    

}
